function f_SLM_gh_solid(app)

calllib('ImageGen', 'Generate_Solid',...
        app.SLM_Image_pointer,...
        app.SLM_ops.width,...
        app.SLM_ops.height,...
        app.BlankPixelValueEditField.Value);
        
app.SLM_Image = f_SLM_poiner_to_im(app, app.SLM_Image_pointer);
app.SLM_Image_plot.CData = app.SLM_Image;

end