function f_SLM_gh_fresnel(app)

calllib('ImageGen', 'Generate_FresnelLens',...
            app.SLM_Image_pointer,...
            app.SLM_ops.width, app.SLM_ops.height,...
            app.FresCenterXEditField.Value,...
            app.FresCenterYEditField.Value,...
            app.FresRadiusEditField.Value,...
            app.FresPowerEditField.Value,...
            app.FresCylindricalCheckBox.Value,...
            app.FresHorizontalCheckBox.Value);
        
app.SLM_Image = f_SLM_poiner_to_im(app, app.SLM_Image_pointer);
app.SLM_Image_plot.CData = app.SLM_Image;
end