function f_SLM_gh_blazed(app)

calllib('ImageGen', 'Generate_Grating',...
        app.SLM_Image_pointer,...
        app.SLM_ops.width,...
        app.SLM_ops.height,...
        app.BlazPeriodEditField.Value,...
        app.BlazIncreasingCheckBox.Value,...
        app.BlazHorizontalCheckBox.Value);
    
app.SLM_Image = f_SLM_poiner_to_im(app, app.SLM_Image_pointer);
app.SLM_Image_plot.CData = app.SLM_Image;
            
end