function f_SLM_gh_stripes(app)

calllib('ImageGen', 'Generate_Stripe',...
            app.SLM_Image_pointer,...
            app.SLM_ops.width,...
            app.SLM_ops.height,...
            app.StripePixelValueEditField.Value,...
            app.StripeGrayEditField.Value,...
            app.StripePixelPerStripeEditField.Value);
        
app.SLM_Image = f_SLM_poiner_to_im(app, app.SLM_Image_pointer);
app.SLM_Image_plot.CData = app.SLM_Image;

end