function f_SLM_xyz_button_add_to_holo(app)

app.UIImagePhaseTable.Data = array2table([app.UIImagePhaseTable.Data.Variables;...
                                        app.PatternnumberEditField.Value,...
                                        app.ZOffsetumEditField.Value,...
                                        app.XdisplacementEditField.Value,...
                                        app.YdisplacementEditField.Value,...
                                        app.ManualNAEditField.Value,...
                                        app.WeightEditField.Value]);

end