function f_SLM_xyz_button_add_to_holo(app)

tab_data = app.UIImagePhaseTable.Data.Variables;

if isempty(tab_data)
    idx = 1;
else
    idx = size(tab_data,1)+1;
    tab_data(:,1) = 1:(idx-1);
end

app.UIImagePhaseTable.Data = array2table([tab_data;...
                                        idx,...
                                        app.PatternnumberEditField.Value,...
                                        app.ZOffsetumEditField.Value,...
                                        app.XdisplacementEditField.Value,...
                                        app.YdisplacementEditField.Value,...
                                        app.ManualNAEditField.Value,...
                                        app.WeightEditField.Value]);
                                    
end